from collections.abc import AsyncGenerator
from http import HTTPStatus

from fastapi import APIRouter, HTTPException, Query, status
from fastapi.responses import StreamingResponse
from src.app.configs.di import github_parser, llm_adapter, vector_adapter
from src.app.schemas.repo import (
    AskQueryInfo,
    AskResponse,
    IngestRepo,
    QueryInfo,
    QueryResponse,
)
from src.app.use_cases.base import ask, ask_stream, ingest, query
from src.app.utils.logger import get_logger

logger = get_logger(__name__)

router = APIRouter(
    prefix="/repo_parser",
    tags=["GitHub Repo Parser"],
)


@router.get(
    "/ask",
    status_code=HTTPStatus.OK,
    description="Ask a natural-language question about an ingested repository",
    summary="Ask LLM about a repository",
    response_model=AskResponse,
)
async def ask_llm(
    llm_adapter: llm_adapter,
    vector_adapter: vector_adapter,
    data: AskQueryInfo = Query(),
) -> AskResponse:
    answer, context_found = await ask(data, vector_adapter, llm_adapter)
    return AskResponse(answer=answer, context_found=context_found)


@router.get(
    "/ask/stream",
    description="Stream tokens as they are generated by the LLM (use curl -N to observe)",
    summary="Ask LLM about a repository (streaming)",
    response_class=StreamingResponse,
)
async def ask_llm_stream(
    llm_adapter: llm_adapter,
    vector_adapter: vector_adapter,
    data: AskQueryInfo = Query(),
) -> StreamingResponse:
    stream, context_found = await ask_stream(data, vector_adapter, llm_adapter)

    async def token_gen() -> AsyncGenerator[str, None]:
        async for token in stream:
            yield token

    return StreamingResponse(
        token_gen(),
        media_type="text/plain",
        headers={"X-Context-Found": str(context_found).lower()},
    )


@router.get(
    "/query",
    status_code=HTTPStatus.OK,
    description="Vector-search the ingested codebase and return matching code chunks",
    summary="Query the knowledge base",
    response_model=QueryResponse,
)
async def query_info(
    vector_adapter: vector_adapter,
    data: QueryInfo = Query(),
) -> QueryResponse:
    items = await query(data, vector_adapter)
    return QueryResponse(
        items=items,
        total=len(items),
        score_threshold_used=data.score_threshold,
    )


@router.post(
    "/ingest",
    status_code=HTTPStatus.ACCEPTED,
    description="Fetch and index all Python files from a GitHub repository",
    summary="Ingest a GitHub repository",
)
async def ingest_repo(
    data: IngestRepo,
    github_parser: github_parser,
    vector_adapter: vector_adapter,
) -> None:
    logger.info("ingest_request owner=%s repo=%s branch=%s", data.owner, data.repo, data.branch)
    try:
        await ingest(data, github_parser, vector_adapter)
    except ValueError as err:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(err),
        ) from err
